In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, classification_report, confusion_matrix
import joblib
import pandas as pd
import numpy as np

In [2]:
featured_df = pd.read_csv("attendance_with_features.csv")
# featured_df.head()

In [3]:
df_model = featured_df.copy()
df_model['date'] = pd.to_datetime(df_model['date'], errors='coerce')

features = ['Count_Telat_7D', 'Count_Alpa_30D', 'Streak_Telat', 'Avg_Arrival_Time_7D']

df_model['has_checkin'] = df_model['checkin_time'].notna().astype(int)
df_model['Lag_1_Status_filled'] = df_model['Lag_1_Status'].fillna('None')
cat_cols = ['DayOfWeek', 'Lag_1_Status_filled']

X_num = df_model[features + ['has_checkin']].copy()
X_num['Avg_Arrival_Time_7D'] = X_num['Avg_Arrival_Time_7D'].fillna(X_num['Avg_Arrival_Time_7D'].median())

X_cat = pd.get_dummies(df_model[cat_cols].astype(str), prefix=cat_cols, drop_first=True)
X = pd.concat([X_num, X_cat], axis=1)
y = df_model['note'].astype(str) 

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [4]:
X_train_nb = X_train.copy()
X_test_nb = X_test.copy()
bool_cols = X_train_nb.select_dtypes(include=['bool']).columns
X_train_nb[bool_cols] = X_train_nb[bool_cols].astype(int)
X_test_nb[bool_cols] = X_test_nb[bool_cols].astype(int)

nb_clf = GaussianNB()
nb_clf.fit(X_train_nb, y_train)

y_pred_nb = nb_clf.predict(X_test_nb)



In [5]:
print(classification_report(y_test, y_pred_nb, zero_division=0))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred_nb))
print(f"Accuracy: {accuracy_score(y_test, y_pred_nb):.6f}")
acc = accuracy_score(y_test, y_pred_nb)
precision = precision_score(y_test, y_pred_nb, average='weighted', zero_division=0)
recall = recall_score(y_test, y_pred_nb, average='weighted', zero_division=0)
f1 = f1_score(y_test, y_pred_nb, average='weighted', zero_division=0)

print("\nAggregate metrics:")
print(f"Accuracy: {acc:.6f}")
print(f"Precision (weighted): {precision:.6f}")
print(f"Recall (weighted): {recall:.6f}")
print(f"F1-score (weighted): {f1:.6f}")

              precision    recall  f1-score   support

        alpa       1.00      0.80      0.89      9246
       hadir       0.89      0.91      0.90     11407
       libur       0.83      1.00      0.91      9402
       telat       0.33      0.28      0.30      1852

    accuracy                           0.87     31907
   macro avg       0.76      0.74      0.75     31907
weighted avg       0.87      0.87      0.86     31907

Confusion matrix:
[[ 7352     0  1894     0]
 [    0 10355     0  1052]
 [    0     0  9402     0]
 [    0  1339     0   513]]
Accuracy: 0.865703

Aggregate metrics:
Accuracy: 0.865703
Precision (weighted): 0.870640
Recall (weighted): 0.865703
F1-score (weighted): 0.862351


In [ ]:
# # simpan model
# joblib.dump(nb_clf, "naive_bayes_attendance_model.joblib")
# print("Model tersimpan -> naive_bayes_attendance_model.joblib")